services:
  frontend:
    build:
      context: ./frontend # path to your React Vite app
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173" # Vite dev server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend # path to your backend app
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Cloud Run listens here
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=8080
